### ISSUE TITLE
Incorrect prepared statement rebuild when using bindValue without an explicit type

### ISSUE THREAD

**Issue by matrey** [adamturcsan/reconnecting-pdo#4]
I used bindValue without an explicit type:
```
            $this->get_item->bindValue(':code', $code);
            $this->get_item->execute();
```
which is permitted:
```
public PDOStatement::bindValue ( mixed $parameter , mixed $value [, int $data_type = PDO::PARAM_STR ] ) : bool
```

But I get this notice when the library tries to re-run bindValue on the re-created prepared statement:
```
PHP Notice:  Undefined offset: 2 in /...redacted.../vendor/legow/reconnecting-pdo/src/ReconnectingPDOStatement.php on line 199
```
And the query result is incorrect. It's likely PHP understands the undefined type as "0", which is actually PDO::PARAM_NULL
```
php > echo PDO::PARAM_NULL ;
0
php > echo PDO::PARAM_STR ;
2
```

**Comment by adamturcsan** [comment]
Thanks for reporting the issue. I was able to reproduce the malfunction. Fix will come soon.

**Comment by adamturcsan** [comment]
I believe the next patch version [1.1.2](https://github.com/adamturcsan/reconnecting-pdo/releases/tag/v1.1.2) fixes this issue

**Comment by matrey** [comment]
@adamturcsan Unfortunately call_user_method_array seem to have been removed in PHP 7

https://www.php.net/manual/en/function.call-user-method-array.php

> This function was DEPRECATED in PHP 4.1.0, and REMOVED in PHP 7.0.0.
> Alternatives to this function include:
> call_user_func_array()

https://www.php.net/manual/en/function.call-user-func-array.php

> (PHP 4 >= 4.0.4, PHP 5, PHP 7)
> call_user_func_array ( callable $callback , array $param_arr ) : mixed

Where callable can be an array ['class name', 'method name']

**Comment by adamturcsan** [comment]
Yeah, sure, I pushed the fix in a rush, I already started to look into other solutions as 'bindParam' only expects references, and as I see, call_user_func_array–as the obvious alternative– doesn't pass them as references....

**Comment by adamturcsan** [comment]
[v1.1.3](https://github.com/adamturcsan/reconnecting-pdo/releases/tag/v1.1.3)

**Comment by matrey** [comment]
I confirm everything is good now, using dev-master on a PHP 7.3.3 system. Thanks!
Though FYI packagist is not up-to-date, still listing v1.1.1 as the most recent version for the library.

**Comment by adamturcsan** [comment]
> Though FYI packagist is not up-to-date, still listing v1.1.1 as the most recent version for the library.

I see v1.1.3, I guess it just needs some time ;)
