### ISSUE TITLE
When server has gone away a long time, will always throw "No PDO connection is set"

### ISSUE THREAD

**Issue by Moln** [adamturcsan/reconnecting-pdo#6]
```php
<?php

use LegoW\ReconnectingPDO\ReconnectingPDO;

include 'vendor/autoload.php';

$config = [
    'dsn' => 'mysql:host=127.0.0.1;dbname=test;charset=utf8mb4',
    'username' => 'root',
    'password' => '',
];

$pdo = new ReconnectingPDO($config['dsn'], $config['username'], $config['password']);

sleep(5);
// In sleep times, do `service mysql stop`

while (true) {
    try {
        $sth = $pdo->prepare('select 1');
        $sth->execute();
        $sth->fetchAll();
    } catch(\Exception $e) {
        // Throw ReconnectingPDOException: No PDO connection is set
        // And a PHP Notice:  Undefined property: LegoW\ReconnectingPDO\ReconnectingPDO::$connection
        echo $e; 
        echo "------------------\n";
    }

    sleep(5);
}
```

Expected result:
----------------

Reconnect, when server was start.

Actual result:
--------------

Throw `ReconnectingPDOException: No PDO connection is set`.

And a `PHP Notice:  Undefined property: LegoW\ReconnectingPDO\ReconnectingPDO::$connection`

**Comment by adamturcsan** [comment]
Hey,
Actually this case is not tested/not targeted, as this lib is mainly for "Mysql server has gone away" type errors for long idling connections.
But it could be a valid use case, if there's the resource to implement it.

And of course #7 is a long overdue task to clarify the misunderstandings...

**Comment by Maxim-Mazurok** [comment]
Yeah, I agree with @adamturcsan 
@Moln can you give a valid use-case or real-world situation when such error occurs?
From my point of view, it's only possible in case if the server is MySQL server is down, which doesn't seem like a good thing in the first place. You probably want to set up monitoring with alerts on your MySQL server to prevent this. Also, you probably should inform your users that the DB is down.
Anyway, I would recommend making PR if you still want to implement this. But please, make this optional. Somebody may not have MySQL alerts in place and will rely on the server log, looking for errors.
Thanks!

**Comment by Moln** [comment]
Thanks guys!

At that time , I'm maintaining and upgrading my Mysql server.
This must stop for a while. Then my daemon program throw an exception ( `No PDO connection is set` ) and exit. 
So I saw the [`ReconnectingPDO.php`](https://github.com/adamturcsan/reconnecting-pdo/blob/34bca1932f67f9e403f1294196386c7ff0257c95/src/ReconnectingPDO.php#L122-L124) code. Then I know , this is just to work for long idling connections.

The last,  I change to use [doctrine/dbal](https://github.com/doctrine/dbal), and using `ping()` and `connect()` instead. Because I read this issue https://github.com/doctrine/dbal/issues/1454
